### ISSUE TITLE
BUG : Can't connect to server

### ISSUE THREAD

**Issue by Alafun** [OI-wiki/OI-wiki-vscode#17]
![image](https://user-images.githubusercontent.com/78416589/151384656-b8f0aa90-5a83-49a2-a071-2130497c1eff.png)

**Comment by abc1763613206** [comment]
请具体提供一下网络环境？     
以及访问 https://search.oi-wiki.org:8443/?s= 的效果

**Comment by Alafun** [comment]
> 请具体提供一下网络环境？

网络就是国内的宽带

访问 [OI-wiki搜索线段树](https://search.oi-wiki.org:8443/?s=线段树)
结果 
![image](https://user-images.githubusercontent.com/78416589/151398777-b138a38d-428d-43ac-93a4-7b7baa6bfeaf.png)

**Comment by Alafun** [comment]
![image](https://user-images.githubusercontent.com/78416589/153129187-0a836f53-6ea1-4f79-8b64-d7fba99d1d9d.png)

**Comment by dustbin1415** [comment]
遇到了同样的问题，请问现在有解决方案了嘛？

**Comment by Alafun** [comment]
> 遇到了同样的问题，请问现在有解决方案了嘛？

你也是这样吗

**Comment by dustbin1415** [comment]
> 你也是这样吗
是的

**Comment by dustbin1415** [comment]
> 你也是这样吗

是的

**Comment by alphagocc** [comment]
https://github.com/axios/axios/issues/4162#issuecomment-980647935

请依据此comment检查证书，（我认为）这不是oiwiki的问题，也不是axios的问题

**Comment by ghost** [comment]
> [axios/axios#4162 (comment)](https://github.com/axios/axios/issues/4162#issuecomment-980647935)
> 
> 请依据此comment检查证书，（我认为）这不是oiwiki的问题，也不是axios的问题

检查了一下，我这里的证书（至少看起来）是没问题的

**Comment by alphagocc** [comment]
https://github.com/microsoft/vscode/issues/136787

答案是上游问题

**Comment by alphagocc** [comment]
VS Code Version 1.66.0 已经修复

**Comment by Enter-tainer** [comment]
目前 VSCode 已经修复了证书错误的问题，升级 VSCode 版本到 1.66.0 即可。暂时 close 该 issue, 如果后续再出现类似问题，将继续在本 issue 中进行追踪
